// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_R6OWdOt6jkHQWbC6nI3eAVvffKk1bU',
    appId: '1:953175183402:web:b2550bd5af02d229d17353',
    messagingSenderId: '953175183402',
    projectId: 'airbnb-a2bee',
    authDomain: 'airbnb-a2bee.firebaseapp.com',
    storageBucket: 'airbnb-a2bee.firebasestorage.app',
    measurementId: 'G-L79K6GEKCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kCZ3PraBVWX9iiWYPozDbloVUVyhyuc',
    appId: '1:953175183402:android:4dea175d5cef0f8fd17353',
    messagingSenderId: '953175183402',
    projectId: 'airbnb-a2bee',
    storageBucket: 'airbnb-a2bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_KgeqBOcCpfa9wfInmLNuSuEmLUbvndY',
    appId: '1:953175183402:ios:249cd5a3e1ba8638d17353',
    messagingSenderId: '953175183402',
    projectId: 'airbnb-a2bee',
    storageBucket: 'airbnb-a2bee.firebasestorage.app',
    iosBundleId: 'com.zero.flutter.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_KgeqBOcCpfa9wfInmLNuSuEmLUbvndY',
    appId: '1:953175183402:ios:249cd5a3e1ba8638d17353',
    messagingSenderId: '953175183402',
    projectId: 'airbnb-a2bee',
    storageBucket: 'airbnb-a2bee.firebasestorage.app',
    iosBundleId: 'com.zero.flutter.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi_R6OWdOt6jkHQWbC6nI3eAVvffKk1bU',
    appId: '1:953175183402:web:70d5ad04503ae952d17353',
    messagingSenderId: '953175183402',
    projectId: 'airbnb-a2bee',
    authDomain: 'airbnb-a2bee.firebaseapp.com',
    storageBucket: 'airbnb-a2bee.firebasestorage.app',
    measurementId: 'G-Y61NLFMGGT',
  );
}
